supabase + .env
SashaMyshkin/nodejs pull request #2
Opened 2023-10-19 20:00 UTC by SashaMyshkin

2023-10-20 20:35 UTC, slavo3dev commented on src/Application.ts
> +class Application {
This needs to be moved to .env ASAP

2023-10-20 20:48 UTC, slavo3dev requested changes

2023-10-20 20:48 UTC, slavo3dev commented on src/db.ts
> +//const database = createClient(process.env["SUPABASE_URL"]!, process.env["SUPABASE_KEY"]!);
```js
const database = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY");
```

this is the way you are calling Variables from env files:
process.env.SUPABASE_URL

process.env["SUPABASE_KEY"]! - this syntax is not valid

2023-10-20 20:48 UTC, slavo3dev commented on src/index.ts
> +dotenv.config();
It probably will work even without dotenv

syntax was wrong

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
> +import database from "../db";
create absolut path

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
> +	const { data, error } = await database.from("todos").insert([{title:title, description:description}]).select();
When property name matches the value you can write title instead of title: title `database.from("todos").insert([{title, description:description}])`

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
> +	const { data, error } = await database
where we are catching errors 

You need to improve error handling.

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
> +	res.send(JSON.stringify(error));
Why are we sending an error as a response if we are successfully delete todo

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
> +	res.send(JSON.stringify(error));
where is the success response? How front end will know that todo is successfully deleted

2023-10-20 20:48 UTC, slavo3dev commented on src/routes/todos.ts
>  	res.send(JSON.stringify(data));
why we are sending data back

2023-10-20 20:48 UTC, slavo3dev commented on src/types/Todo.ts
> +class Todo{
why you are creating a Class 
Which architectural principle are you trying to follow?

2023-10-20 20:48 UTC, slavo3dev commented on src/types/Todo.ts
> +class Todo{
why the file is located inside types, and there are no types or interfaces declared

2023-10-20 20:48 UTC, slavo3dev commented on tsconfig.json
> +    "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
Why this is uncommented and the rest are commented out ??

2023-10-20 20:48 UTC, slavo3dev commented on .gitignore
> +application
you are still committing the application file even you added them differently

2023-10-21 14:41 UTC, SashaMyshkin commented on src/routes/todos.ts
> +	const { data, error } = await database
I added error handling and data validation.

2023-10-21 14:42 UTC, SashaMyshkin commented on src/routes/todos.ts
> +	res.send(JSON.stringify(error));
Success response added.

2023-10-21 14:56 UTC, SashaMyshkin commented on src/routes/todos.ts
>  	res.send(JSON.stringify(data));
I personally prefer to send data back as a success response when it comes to simple inserting and updating data. If there is a better approach or strongly defined programming convention, please let me know.

2023-10-21 15:04 UTC, SashaMyshkin commented on tsconfig.json
> +    "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
If this property is set to true, we receive a warning when attempting to access an object's property using dot notation, in cases where TypeScript expects that property to be accessed using an index signature. I was just experimenting with these properties and left this one uncommented by chance.

2023-10-21 15:08 UTC, SashaMyshkin commented on .gitignore
> +application
Application.ts file in .gitignore added.

2023-10-21 15:11 UTC, SashaMyshkin commented on src/routes/todos.ts
> +	const { data, error } = await database.from("todos").insert([{title:title, description:description}]).select();
Is it conventional to code this way in such a scenario, or can I keep it as I coded?

2023-10-21 15:26 UTC, SashaMyshkin commented on src/types/Todo.ts
> +class Todo{
I'm planning to go with the Object-Relational Mapping (ORM) architectural pattern, which means having a class for each database table. Right now, I might not need this class, but I can see how it'll come in handy as my code gets more complex.

2023-10-22 10:42 UTC, SashaMyshkin commented on src/routes/todos.ts
> +import database from "../db";
Absolute path created.

2023-10-22 11:18 UTC, slavo3dev commented on src/routes/todos.ts
> +	const { data, error } = await database.from("todos").insert([{title:title, description:description}]).select();
Here, { title, description } is the shorthand for { title: title, description: description }. This notation is more concise and is generally preferred in modern JavaScript because it's easier to read and write.

Conciseness: The shorthand notation is more concise, leading to less verbose code.

Readability: It improves readability because when developers see the shorthand, they instantly know that the property and variable names are the same. This reduces the cognitive load.

Modern JS: It's a feature of ES6 (or ES2015) and onwards, and adopting modern language features can make your codebase feel more up-to-date.

Widely Adopted: Most modern codebases and style guides (like Airbnb's) prefer or enforce this shorthand when possible.

2023-10-23 13:08 UTC, SashaMyshkin commented on src/Application.ts
> +class Application {
Problem with .env package resolved.

2023-10-23 13:25 UTC, SashaMyshkin commented on src/index.ts
> +dotenv.config();
Changed.

2023-10-23 13:45 UTC, SashaMyshkin commented on src/routes/todos.ts
> +	const { data, error } = await database.from("todos").insert([{title:title, description:description}]).select();
Thank you, I'll follow that convetion.

2023-11-09 15:21 UTC, merged

2023-11-09 15:21 UTC, SashaMyshkin commented
Documentation added. Everithing seems to be good.